version: '3.8'

services:
  api:
    build: .
    restart: always
    volumes:
      - ./app:/app/app
    ports:
      - "5000:5000/tcp"
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - urlshortner

  db:
    image: amazon/dynamodb-local
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath ./data"
    ports:
      - "8000:8000/tcp"
    restart: always
    volumes:
      - "./db_data:/home/dynamodblocal/data"
    working_dir: /home/dynamodblocal
    networks:
      - urlshortner

  dbadmin:
    image: aaronshaf/dynamodb-admin
    ports:
      - "8001:8001/tcp"
    environment:
      DYNAMO_ENDPOINT: http://db:8000
    depends_on:
      - db
    networks:
      - urlshortner

  dynamodump:
    image: bchew/dynamodump
    volumes:
      - ./db:/dump
    networks:
      - urlshortner

networks:
  urlshortner : {}